# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Startyp 101
tagline:          'A theme'
description:      'Everyday Idea or Idea Everyday'


author:
  name:           'Startup 101'
 

paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/startup101
