# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Startup 101
tagline:          'A theme'
description:      'Everyday Idea or Idea Everyday'


author:
  name:           'Startup 101'
  
contact:
    linkedin:  https://www.linkedin.com/
    github:    https://github.com/startup101
    # facebook:  <hide>
    twitter:   https://twitter.com/
   
 
nav:
  Home:           
    - '/'
  About:          
    - '/about/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
    
paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/startup101

logo:
    image: /public/img/logo.jpg