# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Startup 101
tagline:          'Everyday Ideas or Idea Everyday'
description:      'Everyday Ideas or Idea Everyday'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Startup 101'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/startup101
